<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Payment Due_paymentDueDate</name>
   <tag></tag>
   <elementGuidId>5b7d2494-f055-4a67-84ae-5d22d26d0bc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;paymentDueDate&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='paymentDueDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form >> internal:has-text=&quot;CustomerSteveSharpieBarbieTax ExemptContact NameBar BieEmailPhoneBilling Address&quot;i >> select[name=&quot;paymentDueDate&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>10928850-0727-4474-87f7-b785bdad536c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentDueDate</value>
      <webElementGuid>520d7c8c-febc-4072-9404-6d7215196eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 block w-full py-2 pl-3 pr-10 lg:text-sm md:text-xs text-xs focus:outline-none border-primary-300 focus:border-primary-500 focus:ring-primary-500</value>
      <webElementGuid>7e59a23d-def4-4da7-bc8b-9653f70c46de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>On ReceiptWithin 7 DaysWithin 14 DaysWithin 30 DaysWithin 45 DaysWithin 60 DaysWithin 90 Days</value>
      <webElementGuid>e19f0c9a-4b47-4001-b102-5b9659ac806d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;lg:block md:hidden hidden lg:h-full lg:w-full&quot;]/div[@class=&quot;grid h-full gap-0 grid-cols-6&quot;]/div[@class=&quot;h-full col-span-5&quot;]/div[@class=&quot;mx-4&quot;]/div[@class=&quot;mx-auto max-w-full&quot;]/div[@class=&quot;p-4 space-y-4&quot;]/div[2]/div[@class=&quot;p-4 bg-white rounded-b-xl rounded-tr-xl&quot;]/div[@class=&quot;px-1&quot;]/div[@class=&quot;mx-auto w-full&quot;]/div[@class=&quot;overflow-visible bg-white sm:rounded-lg&quot;]/form[1]/div[@class=&quot;lg:px-6 md:px-4 px-2.5 space-y-6 pb-4&quot;]/div[@class=&quot;flex flex-col space-x-0 space-y-4 lg:flex-row lg:space-x-4 lg:space-y-0 lg:justify-between&quot;]/div[@class=&quot;lg:w-[73%] w-full md:w-full&quot;]/div[@class=&quot;flex flex-col w-full space-y-4&quot;]/div[@class=&quot;flex flex-col space-x-0 space-y-4 lg:flex-row lg:space-x-4 lg:space-y-0 lg:justify-between&quot;]/div[@class=&quot;flex flex-col w-full space-y-4&quot;]/div[1]/select[@class=&quot;mt-1 block w-full py-2 pl-3 pr-10 lg:text-sm md:text-xs text-xs focus:outline-none border-primary-300 focus:border-primary-500 focus:ring-primary-500&quot;]</value>
      <webElementGuid>7e19b988-9e28-4936-a330-1bd759a8c9b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='paymentDueDate']</value>
      <webElementGuid>f50cd5a3-dc44-4073-8a48-5f409c7e739e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div/form/div/div/div/div/div[7]/div[2]/div/select</value>
      <webElementGuid>93f09d61-884d-417c-8860-f4a0f446c686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Due'])[1]/following::select[1]</value>
      <webElementGuid>cc0bcbde-52d8-42be-8a05-0d32c4311cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice Date'])[1]/following::select[1]</value>
      <webElementGuid>c773acb4-8408-485e-ba69-8e315c83691c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Schedule'])[1]/preceding::select[1]</value>
      <webElementGuid>dcc55387-a29c-48ea-881c-9cbecd19ee4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repeat this Invoice'])[1]/preceding::select[1]</value>
      <webElementGuid>e2e8d49a-2382-47ce-bf75-7344794129e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>4104a723-71c2-44c7-84bb-c0766e38b907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'paymentDueDate' and (text() = 'On ReceiptWithin 7 DaysWithin 14 DaysWithin 30 DaysWithin 45 DaysWithin 60 DaysWithin 90 Days' or . = 'On ReceiptWithin 7 DaysWithin 14 DaysWithin 30 DaysWithin 45 DaysWithin 60 DaysWithin 90 Days')]</value>
      <webElementGuid>0e16404c-b6a0-49ad-9ed2-387b0f5dfca1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
