<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Open options_headlessui-menu-item-r5q</name>
   <tag></tag>
   <elementGuidId>e3e2b82f-e2cf-4b45-89a5-0e086ef592e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-menu-item-«r5q»']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-menu-item-«r5q»</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Edit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0d9574fb-9b97-4acb-8f2a-3f7fb5f3970c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover:bg-primary-500 rounded-md cursor-pointer</value>
      <webElementGuid>e96171f5-a949-4930-968b-1bb37a6d6228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-menu-item-«r5q»</value>
      <webElementGuid>63d7a81e-e29f-4da0-9d65-80ed5adae485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>119ec12f-4aea-4117-946a-ceef4072dd70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>68f1c317-3bfe-4bfa-bea7-1771c58bac0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>active focus</value>
      <webElementGuid>5978a755-bb9d-45ae-9fd1-26d7cc54a8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>33d10c9a-3c4d-4517-b7af-2b2404aff361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-menu-item-«r5q»&quot;)</value>
      <webElementGuid>8dfb2760-98ce-4fe7-9d2f-3442adb5928e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='headlessui-menu-item-«r5q»']</value>
      <webElementGuid>24cf4fad-a9a4-4c23-86fa-7e757254bdc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-menu-items-«r3r»']/div</value>
      <webElementGuid>4fc205f6-3c3e-4584-9128-76fda313b60b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open options'])[5]/following::div[2]</value>
      <webElementGuid>dfdda0cc-c042-4f79-a618-51299ed9e4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send'])[5]/following::div[4]</value>
      <webElementGuid>319e93f7-e97a-47df-8988-72ee2580951f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::div[1]</value>
      <webElementGuid>dc4561c7-b08d-4884-ac4f-7de0df1873ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div[2]/div/div/div</value>
      <webElementGuid>fe40e2c3-9b2e-4415-822c-fdbf6aba31f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'headlessui-menu-item-«r5q»' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>4998cbf6-0b5c-4878-8057-15df0b0231a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
