<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Customer_customerID</name>
   <tag></tag>
   <elementGuidId>9675f098-1147-4401-ac1a-302027c241e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;customerID&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='customerID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;customerID&quot;] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>69773e2d-5744-4b37-bd26-d82cd06bfccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerID</value>
      <webElementGuid>80d1cd91-0b2b-4949-9c4d-642cd3de8b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 block w-full py-2 pl-3 pr-10 lg:text-sm md:text-sm focus:outline-none text-xs border-red-300 focus:border-red-500 focus:ring-red-500 bg-red-100</value>
      <webElementGuid>5d7b1ac4-8203-46ef-a7af-a072118af472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SteveSharpieBarbie</value>
      <webElementGuid>d6c32f29-91f4-4e4c-9acb-68222b0064f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;lg:block md:hidden hidden lg:h-full lg:w-full&quot;]/div[@class=&quot;grid h-full gap-0 grid-cols-6&quot;]/div[@class=&quot;h-full col-span-5&quot;]/div[@class=&quot;mx-4&quot;]/div[@class=&quot;mx-auto max-w-full&quot;]/div[@class=&quot;p-4 space-y-4&quot;]/div[2]/div[@class=&quot;p-4 bg-white rounded-b-xl rounded-tr-xl&quot;]/div[@class=&quot;px-1&quot;]/div[@class=&quot;mx-auto w-full&quot;]/div[@class=&quot;overflow-visible bg-white sm:rounded-lg&quot;]/form[1]/div[@class=&quot;lg:px-6 md:px-4 px-2.5 space-y-6 pb-4&quot;]/div[@class=&quot;flex flex-col space-x-0 space-y-4 lg:flex-row lg:space-x-4 lg:space-y-0 lg:justify-between&quot;]/div[@class=&quot;lg:w-[73%] w-full md:w-full&quot;]/div[@class=&quot;flex flex-col w-full space-y-4&quot;]/div[1]/div[@class=&quot;flex rounded-md shadow-sm&quot;]/div[@class=&quot;relative flex flex-grow items-stretch focus-within:z-10&quot;]/select[@class=&quot;mt-1 block w-full py-2 pl-3 pr-10 lg:text-sm md:text-sm focus:outline-none text-xs border-red-300 focus:border-red-500 focus:ring-red-500 bg-red-100&quot;]</value>
      <webElementGuid>b184c343-5109-46c0-b1c1-9d5e3601c046</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='customerID']</value>
      <webElementGuid>a3e1755d-ec8e-4256-bc26-d5c2df6ffdf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div/form/div/div/div/div/div/div/div/select</value>
      <webElementGuid>02b8bf28-9a26-47b7-a497-dcfa56906d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[1]/following::select[1]</value>
      <webElementGuid>91cc9a33-8f6d-4fe0-a945-35c3eadc31af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice'])[3]/following::select[1]</value>
      <webElementGuid>b15ba33c-63b3-4ff7-aaa1-54c9291809ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer field is Required'])[1]/preceding::select[1]</value>
      <webElementGuid>dab19654-d692-45f3-beb0-8ae5424c0b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Ref'])[1]/preceding::select[1]</value>
      <webElementGuid>0b066d14-f8fc-4a3a-a5c0-47e2922e363a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3a65ebbd-5f24-4d66-8e83-d4edfaa81b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'customerID' and (text() = 'SteveSharpieBarbie' or . = 'SteveSharpieBarbie')]</value>
      <webElementGuid>7acee0a5-bdd2-4996-9a25-4eadb5af9f71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
