<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Void_headlessui-menu-item-r73</name>
   <tag></tag>
   <elementGuidId>95b0935e-6a4a-4b3a-89d3-86edcf83b52c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-menu-item-«r73»']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-menu-item-«r73»</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Export to PDF&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fbfea46a-a2b3-48a0-984f-9440d4a780a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover:bg-primary-500 rounded-md cursor-pointer</value>
      <webElementGuid>538a1d26-4042-4a65-b7f0-fbe02e845867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-menu-item-«r73»</value>
      <webElementGuid>d5525175-7fc5-46e3-87f3-c2af0322e61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>50c74dc5-f805-4483-b745-3b46867251c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>333e1a4c-e337-4db3-8b0a-bd539ed382e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>active focus</value>
      <webElementGuid>f53f8b14-a45b-46f1-8bf5-0f4308194231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Export to PDF</value>
      <webElementGuid>0cfb55ba-8994-43e8-bf8c-cd75d06313c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-menu-item-«r73»&quot;)</value>
      <webElementGuid>fd261f17-56a0-4090-965c-23fcb0ced58b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='headlessui-menu-item-«r73»']</value>
      <webElementGuid>45914cef-cc20-45c8-8f7f-c42406a8ee04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-menu-items-«r4j»']/div[6]</value>
      <webElementGuid>b1b4fa58-1034-488c-98c8-90451da6f12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Void'])[1]/following::div[1]</value>
      <webElementGuid>08804f3b-7a74-4edd-859f-42731bad1bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post'])[2]/following::div[2]</value>
      <webElementGuid>baf77eac-07c2-476d-9d61-39961a327646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::div[2]</value>
      <webElementGuid>87f02a18-d4c0-4724-b4e7-6e47222633eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div[2]/div/div/div[6]</value>
      <webElementGuid>65d312de-eb2b-40db-a938-fe38b8a75521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'headlessui-menu-item-«r73»' and (text() = 'Export to PDF' or . = 'Export to PDF')]</value>
      <webElementGuid>a5f0e912-0430-4f36-afd6-2f8246b0026a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
