<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Send Estimate_lgw-6 lgh-6 mdw-6 mdh-6 w-5 h-5</name>
   <tag></tag>
   <elementGuidId>d98b4f34-0204-4077-90e8-7a2d0b24d48d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Send Estimate'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;headlessui-dialog-panel-«rdo»&quot;] >> internal:role=button >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>60c3c994-44d1-4dfa-897d-0c816b504850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>54a62442-cd90-427a-814e-38430beb79fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>58fc1df4-eddf-4aba-8090-435c8724aec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>48c507d7-4a6a-49f5-88b1-b905d3254942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>1.5</value>
      <webElementGuid>58cf83a6-8721-4cbd-aa88-e1bdf070a6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>202603d2-d87e-4080-867c-3070065d3dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lg:w-6 lg:h-6 md:w-6 md:h-6 w-5 h-5</value>
      <webElementGuid>46bb4b50-3b42-417c-ae09-446967743f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-panel-«rdo»&quot;)/div[@class=&quot;flex pl-4 justify-between items-center&quot;]/div[2]/div[@class=&quot;flex justify-end&quot;]/button[@class=&quot;hover:text-red-500 p-2&quot;]/svg[@class=&quot;lg:w-6 lg:h-6 md:w-6 md:h-6 w-5 h-5&quot;]</value>
      <webElementGuid>03be87e2-f361-4c31-891e-0fefb0d122c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send Estimate'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>23a0a10a-b08b-4d9a-9d3b-40dd7787f735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(7 items)'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>43f34050-1277-4a13-8920-918893b63efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Link'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>7dde313a-721a-45e6-bf8e-6738138cacca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A link to your Estimate with all details included'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>c9743a64-237d-403f-a559-339707cfbd18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
