<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Duplicate_headlessui-menu-item-r6r</name>
   <tag></tag>
   <elementGuidId>f48eb056-97af-43ab-b4e7-331ecc216553</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-menu-item-«r6r»']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-menu-item-«r6r»</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Post&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3c13e839-0e6a-42c3-9876-e2f3837c746f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover:bg-primary-500 rounded-md cursor-pointer</value>
      <webElementGuid>5e3538f2-4352-4d3b-b412-e3cbed095dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-menu-item-«r6r»</value>
      <webElementGuid>dff49e33-042e-46a0-bba7-70c26c611774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>48c372a8-8c32-42f1-9068-269cd55c95b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c0d820b3-c410-4d73-bcb9-8053e3e9042e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>active focus</value>
      <webElementGuid>059be237-de93-4885-ad59-653242751e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Post</value>
      <webElementGuid>0b2b2819-99cf-4df7-9608-09c427777bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-menu-item-«r6r»&quot;)</value>
      <webElementGuid>38870feb-0fdf-4ffe-9026-5acff0a2a30c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='headlessui-menu-item-«r6r»']</value>
      <webElementGuid>f859532a-c0e0-4813-8359-4f4b76a9458f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-menu-items-«r4p»']/div[4]</value>
      <webElementGuid>6b510cec-4274-442a-88dd-37f2c89cd0d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duplicate'])[1]/following::div[1]</value>
      <webElementGuid>49c8be73-9e39-4d3f-8ea6-76abad558a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/following::div[2]</value>
      <webElementGuid>37258724-30ee-4218-8009-947a0971bbe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Void'])[1]/preceding::div[1]</value>
      <webElementGuid>1edcbfe8-03ba-4231-adad-3295c2cd1309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div[2]/div/div/div[4]</value>
      <webElementGuid>c7a1dfce-abb7-4dda-911a-d39af4a85bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'headlessui-menu-item-«r6r»' and (text() = 'Post' or . = 'Post')]</value>
      <webElementGuid>1e31cb6c-8a5d-48aa-8edf-bf784ffd832d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
