<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Edit_headlessui-menu-item-r6p</name>
   <tag></tag>
   <elementGuidId>c51fdb4b-54ee-4069-90fb-9635e7a16509</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-menu-item-«r6p»']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-menu-item-«r6p»</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;View&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1e7a333c-6c6d-4424-abbb-157b9c663019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover:bg-primary-500 rounded-md cursor-pointer</value>
      <webElementGuid>74121d9a-3f1e-4980-adb9-49bfdbfa87d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-menu-item-«r6p»</value>
      <webElementGuid>6fa7bade-0376-4cbb-b11a-46200f8c469c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>e7bb1a4e-0f28-4279-93cc-b1cccdf3581d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c5ced937-55c7-4644-9e7b-e225342b414a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>active focus</value>
      <webElementGuid>132f1e72-5d85-4893-a492-2a112010e97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>164ee0d2-1b16-4641-ba95-3800693fe380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-menu-item-«r6p»&quot;)</value>
      <webElementGuid>56cc1a17-e049-45c6-b257-219fbb6e6f1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='headlessui-menu-item-«r6p»']</value>
      <webElementGuid>80b4c558-f082-4f19-9ce2-a91a7cb76097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-menu-items-«r4p»']/div[2]</value>
      <webElementGuid>75341bc2-dcb5-47e7-80b6-46137fccd1cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::div[1]</value>
      <webElementGuid>3c8dc5fc-597f-4663-bd23-9eafe6f63d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open options'])[5]/following::div[3]</value>
      <webElementGuid>0f16cd6b-bb7b-4ba8-845d-5e50eb26c1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duplicate'])[1]/preceding::div[1]</value>
      <webElementGuid>9d8fb782-3495-41ab-809c-8ca000ec0666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div[2]/div/div/div[2]</value>
      <webElementGuid>7abff27f-99fe-414d-b19f-ecce1d97a566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'headlessui-menu-item-«r6p»' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>daf23f8b-b813-4f78-8bfa-bdf6a08a7e37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
